--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: demo
    env: test
  name: mypod
spec: 
  containers: 
    - 
      image: nginx
      name: nginx
      ports: 
        - 
          containerPort: 80
          name: http
          protocol: TCP

